"""empty message

Revision ID: 6ec303f14040
Revises: 96dfbf898218
Create Date: 2020-07-08 15:37:54.654453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec303f14040'
down_revision = '96dfbf898218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('abbreviated_name', sa.String(), nullable=False))
    op.add_column('businesses', sa.Column('accounting_software', sa.String(), nullable=False))
    op.drop_column('businesses', 'name_abbr')
    op.drop_column('businesses', 'acc_sftw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('acc_sftw', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('businesses', sa.Column('name_abbr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('businesses', 'accounting_software')
    op.drop_column('businesses', 'abbreviated_name')
    # ### end Alembic commands ###
