"""empty message

Revision ID: 96dfbf898218
Revises: 7358041b7382
Create Date: 2020-06-29 10:11:20.711612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dfbf898218'
down_revision = '7358041b7382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_abbr', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('revenue', sa.String(), nullable=False),
    sa.Column('acc_sftw', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('countries',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    op.drop_table('businesses')
    # ### end Alembic commands ###
